org: lbibera
app: headhuntr
service: candidate-search

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  deploymentBucket:
    name: ${self:custom.deploymentBucketName}
  runtime: python3.9
  apiGateway:
    restApiId:
      'Fn::ImportValue': sls-${self:custom.sharedService}-${sls:stage}-SFEOutputApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': sls-${self:custom.sharedService}-${sls:stage}-SFEOutputApiGatewayRestApiRootResourceId
  tracing:
    lambda: true
  environment:
    CANDIDATE_SEARCH_TABLE_NAME: !Ref userSearchTable
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
          Resource:
            Fn::GetAtt: [ userSearchTable, Arn ]

plugins:
  - serverless-plugin-lambda-insights
  - serverless-deployment-bucket

custom:
  sharedService: shared
  deploymentBucketName: hhv2.deployment.artifacts
  lambdaInsights:
    defaultLambdaInsights: true

package:
  patterns:
    - '!README.md'
    - '!schema/**'

functions:
  create:
    handler: create.handle
    layers:
      - 'Fn::ImportValue': sls-${self:custom.sharedService}-${sls:stage}-PythonsharedLambdaLayerQualifiedArn
    events:
      - http:
          method: POST
          path: /candidate-search
          request:
            schemas:
              application/json:
                schema: ${file(schema/create_request.json)}
                name: CreateSearchRequestModel
                description: 'Create a new Search'

resources:
 Resources:
  userSearchTable:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: ${sls:stage}_user_search
       AttributeDefinitions:
         - AttributeName: id
           AttributeType: S
       KeySchema:
         - AttributeName: id
           KeyType: HASH
       ProvisionedThroughput:
         ReadCapacityUnits: 1
         WriteCapacityUnits: 1
 Outputs:
  CandidateSearchTableName:
    Description: "The DynamoDB Table name for storing Candidate Search details"
    Value:
      Ref: userSearchTable
    Export:
      Name: !Sub "${AWS::StackName}-CandidateSearchTableName"
